name: Node.js CI

on:
  pull_request:
    branches: [dev]

env:
  CUSTOM_ENV_VAR: ${{ secrets.dev_ENV }} # 전역 환경 변수 설정

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: npx prisma generate
      - name: Run tests
        run: yarn test

      - name: Run E2E tests
        run: yarn test:e2e
        env:
          E2E_TEST_ENV: ${{ env.CUSTOM_ENV_VAR }}
